settings:
  title: 'Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: 博客
    description: '博客' # default=empty
    url: 'https://seeizo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: static.seeizo.com
    name: 静态资源
    description: 'Built for anything connected to the Internet.'
    url: 'https://static.seeizo.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
